name: Many artifacts

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo `date` > world.txt
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-0
        path: world.txt
    
    # This is a small zip file, but a 1MB file inside it.
    - run: dd if=/dev/zero of=small-zip.txt count=1024 bs=1024
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-2
        path: small-zip.txt
  
    # This is a 1MB zip file, and 1MB file inside it.
    - run: dd if=/dev/urandom of=large-zip.txt count=1024 bs=1024
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-3
        path: large-zip.txt

    # This is a small zip file, but a 1MB file inside it.
    - run: |
        dd if=/dev/zero of=small-zip.txt count=1024 bs=1024
        zip small-zip.zip small-zip.txt
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-4
        path: small-zip.zip
        
    - run: |
        mkdir /tmp/test-dir
        echo `date` > /tmp/test-dir/1-world.txt
        echo `date` > /tmp/test-dir/2-world.txt
        echo `date` > /tmp/test-dir/3-world.txt
        
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-folder
        path: /tmp/test-dir/
    
    # This is one artifact
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-6
        path: world.txt
    
    # This is a different artifact but the same name
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-6
        path: /tmp/test-dir/2-world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-8
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-9
        path: world.txt
 
